In [6]:
import tensorflow as tf
import numpy as np

## Random tensor dengan shape (5,5)

In [20]:
random_tensor = np.around(tf.random.normal([5,5]))

In [21]:
random_tensor

array([[-0., -1., -1., -1.,  0.],
       [-1., -1.,  0., -3., -2.],
       [-0., -0., -0.,  0., -1.],
       [ 1., -1.,  2.,  2.,  0.],
       [-0.,  0.,  0.,  1., -1.]], dtype=float32)

## Tensor bilangan prima dengan shape (5,5)

In [22]:
list = [[1, 2, 3, 5, 7], [11, 13, 17, 19, 23], [29, 31, 37, 41, 43], [47, 53, 59, 61, 71], [73, 79, 83, 89, 97]]

In [23]:
prime_tensor = tf.convert_to_tensor(list, dtype=tf.float32)

In [24]:
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  5.,  7.],
       [11., 13., 17., 19., 23.],
       [29., 31., 37., 41., 43.],
       [47., 53., 59., 61., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

## Dimensi ketiga Tensor

In [25]:
random_tensor.shape

(5, 5)

In [26]:
prime_tensor.shape

TensorShape([5, 5])

In [87]:
genap_tensor.shape

TensorShape([5, 5])

## Perhitungan Aritmatika dua Variable

In [100]:
a = random_tensor
b = prime_tensor

jumlah = tf.add(a, b)
kurang = tf.subtract(a, b)
kali = tf.multiply(a, b)
bagi = tf.divide(a, b)
pangkat = tf.pow(a, b)

In [101]:
print(jumlah)

tf.Tensor(
[[ 1.  1.  2.  4.  7.]
 [10. 12. 17. 16. 21.]
 [29. 31. 37. 41. 42.]
 [48. 52. 61. 63. 71.]
 [73. 79. 83. 90. 96.]], shape=(5, 5), dtype=float32)


In [102]:
print(kurang)

tf.Tensor(
[[ -1.  -3.  -4.  -6.  -7.]
 [-12. -14. -17. -22. -25.]
 [-29. -31. -37. -41. -44.]
 [-46. -54. -57. -59. -71.]
 [-73. -79. -83. -88. -98.]], shape=(5, 5), dtype=float32)


In [103]:
print(kali)

tf.Tensor(
[[ -0.  -2.  -3.  -5.   0.]
 [-11. -13.   0. -57. -46.]
 [ -0.  -0.  -0.   0. -43.]
 [ 47. -53. 118. 122.   0.]
 [ -0.   0.   0.  89. -97.]], shape=(5, 5), dtype=float32)


In [104]:
print(bagi)

tf.Tensor(
[[-0.         -0.5        -0.33333334 -0.2         0.        ]
 [-0.09090909 -0.07692308  0.         -0.15789473 -0.08695652]
 [-0.         -0.         -0.          0.         -0.02325581]
 [ 0.0212766  -0.01886792  0.03389831  0.03278688  0.        ]
 [-0.          0.          0.          0.01123596 -0.01030928]], shape=(5, 5), dtype=float32)


In [105]:
print(pangkat)

tf.Tensor(
[[-0.0000000e+00  1.0000000e+00 -1.0000000e+00 -1.0000000e+00
   0.0000000e+00]
 [-1.0000000e+00 -1.0000000e+00  0.0000000e+00 -1.1622615e+09
  -8.3886080e+06]
 [-0.0000000e+00 -0.0000000e+00 -0.0000000e+00  0.0000000e+00
  -1.0000000e+00]
 [ 1.0000000e+00 -1.0000000e+00  5.7646075e+17  2.3058430e+18
   0.0000000e+00]
 [-0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00
  -1.0000000e+00]], shape=(5, 5), dtype=float32)


## Nilai Maksimal dan Minimal dari variable random_tensor

In [106]:
print("Maksimal : ",tf.argmax(random_tensor))
print("Minimal : ",tf.argmin(random_tensor))

Maksimal :  tf.Tensor([3 2 3 3 0], shape=(5,), dtype=int64)
Minimal :  tf.Tensor([1 0 0 1 1], shape=(5,), dtype=int64)


## Penggabungan Ketiga tensor

In [97]:
print(tf.concat([random_tensor, prime_tensor, genap_tensor],axis=0))

tf.Tensor(
[[-0. -1. -1. -1.  0.]
 [-1. -1.  0. -3. -2.]
 [-0. -0. -0.  0. -1.]
 [ 1. -1.  2.  2.  0.]
 [-0.  0.  0.  1. -1.]
 [ 1.  2.  3.  5.  7.]
 [11. 13. 17. 19. 23.]
 [29. 31. 37. 41. 43.]
 [47. 53. 59. 61. 71.]
 [73. 79. 83. 89. 97.]
 [ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]
 [32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50.]], shape=(15, 5), dtype=float32)


## Sorting Descending Ketiga Tensor

### Sorting random_tensor

In [80]:
print("Sebelum di sorting secara descending",random_tensor)
rs = tf.sort(random_tensor, direction="DESCENDING")
print("Sesudah di sorting secara descending",rs)

Sebelum di sorting secara descending [[-0. -1. -1. -1.  0.]
 [-1. -1.  0. -3. -2.]
 [-0. -0. -0.  0. -1.]
 [ 1. -1.  2.  2.  0.]
 [-0.  0.  0.  1. -1.]]
Sesudah di sorting secara descending tf.Tensor(
[[-0.  0. -1. -1. -1.]
 [ 0. -1. -1. -2. -3.]
 [-0. -0. -0.  0. -1.]
 [ 2.  2.  1.  0. -1.]
 [ 1. -0.  0.  0. -1.]], shape=(5, 5), dtype=float32)


### Sorting prima_tensor

In [82]:
print("Sebelum di sorting secara descending",prime_tensor)
ps = tf.sort(prime_tensor, direction="DESCENDING")
print("Sesudah di sorting secara descending",ps)

Sebelum di sorting secara descending tf.Tensor(
[[ 1.  2.  3.  5.  7.]
 [11. 13. 17. 19. 23.]
 [29. 31. 37. 41. 43.]
 [47. 53. 59. 61. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)
Sesudah di sorting secara descending tf.Tensor(
[[ 7.  5.  3.  2.  1.]
 [23. 19. 17. 13. 11.]
 [43. 41. 37. 31. 29.]
 [71. 61. 59. 53. 47.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)


### Sorting genap_tensor

In [98]:
print("Sebelum di sorting secara descending",genap_tensor)
gs = tf.sort(prime_tensor, direction="DESCENDING")
print("Sesudah di sorting secara descending",gs)

Sebelum di sorting secara descending tf.Tensor(
[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]
 [32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50.]], shape=(5, 5), dtype=float32)
Sesudah di sorting secara descending tf.Tensor(
[[ 7.  5.  3.  2.  1.]
 [23. 19. 17. 13. 11.]
 [43. 41. 37. 31. 29.]
 [71. 61. 59. 53. 47.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
